version: '3.8'

services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    environment:
      - TZ=Asia/Bangkok
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
      - LDAP_CONFIG_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ROOT=${LDAP_ROOT}
      - LDAP_ADMIN_DN=${LDAP_ADMIN_DN}
      - LDAP_PORT_NUMBER=${LDAP_PORT_NUMBER}
      - LDAP_ENABLE_TLS=${LDAP_ENABLE_TLS}
      #- LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/public.crt
      #- LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/private.key
      #- LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/ca.crt
      #- LDAP_TLS_DH_PARAMS_FILE=/opt/bitnami/openldap/certs/dhparams.pem
    ports:
      - "389:1389"
      - "636:1636"
    volumes:
      - openldap_data:/bitnami/openldap
    networks:
      - openldap-network
      
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      - TZ=Asia/Bangkok
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      #- PHPLDAPADMIN_HTTPS=false
      - LDAP_ENABLE_TLS=${LDAP_ENABLE_TLS}
    volumes:
      - phpldapadmin_data:/var/www/phpldapadmin
    ports:
      - "10443:443"   # Port for accessing phpLDAPadmin
    depends_on:
      - openldap
    networks:
      - openldap-network
      
networks:
  openldap-network:
volumes:
  openldap_data:
    driver: local
  phpldapadmin_data:
    driver: local
